### ISSUE TITLE
Examples don't run

### ISSUE THREAD

**Issue by 007-JB** [deedy5/requests_tor#6]
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
from requests_tor import RequestsTor
rt = RequestsTor(tor_ports=(9000, 9001, 9002, 9003, 9004), autochange_id=1)
urls = (f'https://habr.com/ru/post/{x}' for x in range(1, 50))
r = rt.get_urls(urls)
print(r[-1].text)
Traceback (most recent call last):
  File "<input>", line 6, in <module>
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 105, in get_urls
    temp_results = [resp for resp in
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 105, in <listcomp>
    temp_results = [resp for resp in
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 445, in result
    return self.__get_result()
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 77, in get
    return self.request(method, url, **kwargs)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 69, in request
    resp = requests.request(method, url, **kwargs, proxies=proxies)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 412, in send
    conn = self.get_connection(request.url, proxies)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 309, in get_connection
    proxy_manager = self.proxy_manager_for(proxy)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 182, in proxy_manager_for
    manager = self.proxy_manager[proxy] = SOCKSProxyManager(
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 47, in SOCKSProxyManager
    raise InvalidSchema("Missing dependencies for SOCKS support.")
requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.

**Comment by 007-JB** [comment]
PS - I tried installing pysocks, no luck:
pip install pysocks

see here: https://github.com/conda/conda/issues/3505

**Comment by deedy5** [comment]
Try this solution:
```
pip install -U requests_tor --ignore-installed
```

**Comment by 007-JB** [comment]
Tried that, installed correctly, ran "simple application" and received following error(s):
Traceback (most recent call last):
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\socks.py", line 787, in connect
    super(socksocket, self).connect(proxy_addr)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\contrib\socks.py", line 96, in _new_conn
    conn = socks.create_connection(
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\socks.py", line 209, in create_connection
    raise err
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\socks.py", line 199, in create_connection
    sock.connect((remote_host, remote_port))
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\socks.py", line 47, in wrapper
    return function(*args, **kwargs)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\socks.py", line 800, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy localhost:9050: [WinError 10061] No connection could be made because the target machine actively refused it
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\connection.py", line 353, in connect
    conn = self._new_conn()
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\contrib\socks.py", line 127, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001D897012850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /anything (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001D897012850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 7, in <module>
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 77, in get
    return self.request(method, url, **kwargs)
  File "C:\Users\jbard\AppData\Local\Programs\Python\Python39\lib\site-packages\requests_tor.py", line 69, in request
    resp = requests.request(method, url, **kwargs, proxies=proxies)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\jbard\PycharmProjects\Parallel\venv\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='httpbin.org', port=443): Max retries exceeded with url: /anything (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x000001D897012850>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by deedy5** [comment]
> socks.ProxyConnectionError: Error connecting to SOCKS5 proxy localhost:9050: [WinError 10061] No connection could be made because the target machine actively refused it

Your socks port 9050 is not responding.
